# Generated by Django 5.2.17 on 2026-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_article_image_partner_image_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Produk Olahan Berkualitas Sejak 1970', max_length=200)),
                ('hero_subtitle', models.CharField(default='BPOM • Halal • NKV • HACCP', max_length=255)),
                ('hero_cta', models.CharField(default='Lihat Katalog', max_length=100)),
                ('company_title', models.CharField(default='Tentang Baso Karawaci', max_length=200)),
                ('company_description', models.TextField(default='Berdiri sejak 1970, PT Anugrah Citra Boga menghadirkan produk olahan berkualitas seperti bakso, sosis, dan olahan ikan dengan komitmen pada kualitas dan keamanan pangan.')),
                ('products_title', models.CharField(default='Produk Terbaik Kami', max_length=200)),
                ('categories_title', models.CharField(default='Kategori Produk', max_length=200)),
                ('testimonials_title', models.CharField(default='Ulasan Pelanggan', max_length=200)),
                ('distribution_title', models.CharField(default='Temukan Distributor & Agen Terdekat', max_length=200)),
                ('articles_title', models.CharField(default='Kabar Terkini', max_length=200)),
                ('marketplace_title', models.CharField(default='Belanja di Marketplace', max_length=200)),
                ('tokopedia_url', models.URLField(blank=True)),
                ('shopee_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='© PT Anugrah Citra Boga — Baso Karawaci, Karawaci, Tangerang', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
