# Generated by Django 5.2.17 on 2026-10-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='URL background hero (kosongkan untuk gradient default)'),
        ),
    ]
