# Generated by Django 5.2.17 on 2026-10-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_sitecontent_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload gambar hero (prioritas di atas URL)', null=True, upload_to='hero/'),
        ),
    ]
